name: Auto Merge

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  enable-automerge:
    if: startsWith(github.event.pull_request.head.ref, 'autofix/') || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
